/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#424754",
        "primary-fixed": "#d8e2ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad7",
        "on-error": "#ffffff",
        "secondary-fixed": "#d4e4fa",
        "primary": "#0058be",
        "primary-container": "#2170e4",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#410004",
        "surface-variant": "#e0e3e5",
        "inverse-primary": "#adc6ff",
        "secondary": "#516072",
        "background": "#f7f9fb",
        "primary-fixed-dim": "#adc6ff",
        "tertiary": "#b61722",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fefcff",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#ffb3ad",
        "error-container": "#ffdad6",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#39485a",
        "on-secondary-container": "#556477",
        "surface-tint": "#005ac2",
        "on-primary-fixed": "#001a42",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#da3437",
        "outline": "#727785",
        "on-primary-fixed-variant": "#004395",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed-dim": "#b9c8de",
        "on-secondary-fixed": "#0d1c2d",
        "outline-variant": "#c2c6d6",
        "on-tertiary-fixed-variant": "#930013",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "secondary-container": "#d2e1f7",
        "matrix-urgent": "#EF4444",
        "matrix-schedule": "#3B82F6",
        "matrix-delegate": "#F97316",
        "matrix-eliminate": "#94A3B8"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"}
    },
  },
  plugins: [],
}